### ISSUE TITLE
Tokens that errors due to Exception not visible in Picas Database views

### ISSUE THREAD

**Issue by hailihu** [sara-nl/picasclient#24]
If an Exception is thrown during processing of a token, the token is saved in the Picas database with `lock=-1` and `done=-1`. However, the Error view in the database assumes `lock>0 && done>0`, and hence the tokens are not visible here. None of the other views display these tokens either, not even `overview_total`.

**Comment by lnauta** [comment]
Interesting that this was not caught before. We should ask @natalieda as this piece of code has been used since the beginning and the resulting tokens are in many DBs.

**Comment by lnauta** [comment]
@natalieda mentioned: "the proposed error view example was almost always modified for the user projects to reflect their applicable exit error codes, thus this has not been an issue for those who got our consultancy. But you are right that we should catch the default case for those who just follow our examples and fix this"

**Comment by lnauta** [comment]
Merged  #25
