### ISSUE TITLE
SSLEOFError

### ISSUE THREAD

**Issue by hailihu** [sara-nl/picasclient#31]
When submitting Tropomi PiCaS jobs to Spider, it frequently (but not always) happens that a run is interrupted by an SSL EOF error. The error is difficult to reproduce as it only happens sometimes, and only for long-running jobs.
```
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2426)
```
The token then stays in a locked state.

The error occurs in `actors.py`, when saving the token to the database:
```
  File "XXX/actors.py", line 74, in _run
    self.db.save(task)
```

I suspect that this code block in `actors.py` is causing problems:
```
        while True:
            try:
                self.db.save(task)
                break
            except ResourceConflict:
                # simply overwrite changes - model results are more
                # important
                new_task = self.db.get(task.id)
                task['_rev'] = new_task.rev
```
It seems that the `while True` only ends when the token can be saved in the db?

**Comment by lnauta** [comment]
Oof, yeah I saw that piece of code before and I do not like it.

**Comment by hailihu** [comment]
I am doing tests without the while loop, see if that changes things.

**Comment by hailihu** [comment]
> I am doing tests without the while loop, see if that changes things.

The Tropomi PiCaS jobs run without problems with the `while True` removed. #32 fixes this error.
